### ISSUE TITLE
Pipeline to output NWB2 file

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#164]
Scope out required work.
Make epics and issues as appropriate.

~~Request new .dat and .abf files from collaborators for conversion and validation.~~ see #285 

Update Ephys Feature Extraction module to write the output file as NWB2
Write nwb2 only when input is nwb2.
Use pynwb_validate for validation

- [x] read-and-append interface to ipfx nwb2 files. This should implement set_spike_times
- [x] A function which constructs either the above class or allensdk.core.nwb_data_set.NwbDataSet from a path. Logic for inferring nwb version is here.
 - [x] roundtrip test for set_spike_times
- [x] accessor methods for reading spikes (needed for roundtrip tests)

**Comment by wbwakeman** [comment]
http://confluence.corp.alleninstitute.org/display/~sergeyg/NWB2+processing+by+the+IVSCC+ephys+pipeline

**Comment by NileGraddis** [comment]
adding myself per discussion in sprint planning

**Comment by NileGraddis** [comment]
@sgratiy could you tell me if:
1. this is correct
2. completing the work laid out here is sufficient to close this issue.
3. the design seems sensible

### goals

The ipfx pipeline should, if run with NWB2 input data, output an NWB2 files containing extracted features.

### background
The feature extraction stage (fx) runs at the end of the ipfx pipeline. It takes as input an NWB file and, after running successfully, generates a copy of the NWB file that contains detected spike times. The code that does this is here:
https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/bin/run_feature_extraction.py#L19

Although fx can read NWB 1 or 2 files using
https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/data_set_utils.py#L6
`embed_spike_times` can only append to NWB 1 files.

Tests for NWB2 writing live here:
https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/tests/test_nwb1_nwb2_conversion.py

There are the following existing NWB interfaces:
- [NwbReader](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/nwb_reader.py). NWB1 & NWB2. RO.
- [NWBDataset](https://github.com/AllenInstitute/AllenSDK/blob/a06728262f82bc92e0865311b7b82891edc11a06/allensdk/core/nwb_data_set.py#L40). NWB1. RW.

and some higher-level interfaces on top of NwbReader (and inheriting from [EphysDataSet](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/ephys_data_set.py#L9)):
- [HbgDataSet](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/hbg_dataset.py#L9). NWB2. RO.
- [AibsDataSet](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/aibs_data_set.py#L11). NWB1. RO.

### suggested implementation

`embed_spike_times` operates by instantiating an (nwb1-specific) `NwbDataSet` and then calling `set_spike_times` on that object. We simply need to ensure that `embed_spike_times` constructs a nwb version-appropriate dataset object and implement embed_spike_times for the nwb 2 class.

One potential complication is that pynwb might have trouble appending to an existing file (at the very least we may need to [repack](https://support.hdfgroup.org/HDF5/doc/RM/Tools.html#Tools-Repack) it). If this turns out to be a problem we might be able to get around it by reading the whole file into memory as an `NWBFile` and modifying that object.

So we need:
- [ ] A read-and-append interface to ipfx nwb2 files. This should implement [`set_spike_times`](https://github.com/AllenInstitute/AllenSDK/blob/a06728262f82bc92e0865311b7b82891edc11a06/allensdk/core/nwb_data_set.py#L258)
- [ ] A function which constructs either the above class or `allensdk.core.nwb_data_set.NwbDataSet`  from a path. Logic for inferring nwb version [is here](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/ipfx/nwb_reader.py#L660).
- [ ] [a roundtrip test](https://github.com/AllenInstitute/ipfx/blob/664f9f3578fe9a34f27c80b742b2af91459521c7/tests/test_nwb1_nwb2_conversion.py) for `set_spike_times` 

### New data
We also need to get new .dat and .abf and check that the pipeline works with them. It sounds like the steps here are:
- [ ] request the files
- [ ] request detailed information on how these data differ from the old ones
- [ ] get the files
- [ ] run them through the pipeline
- [ ] make issues for whatever breaks

**Comment by NileGraddis** [comment]
breaking new data work into another epic ...

**Comment by sgratiy** [comment]
1. Yes
2. Yes
3. Yes

**Comment by NileGraddis** [comment]
OK cool. How do you want to break this work up?

**Comment by sgratiy** [comment]
I will take care of it.
