### ISSUE TITLE
Correct stimulus ontology to avoid manually specifying stimulus tags

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#166]

**Comment by wbwakeman** [comment]
Consider using REST endpoint so that strategy can call one codebase, and it can also be called by external programmer/developer to ensure using the same code to get the ontology.

Alternative: Track ontology files as well known file records.  Can still implement code accessible within/outside LIMS to "get most recent ontology file".
This option also allows a single experiment to track the state of the ontology that is needed for that experiment, even for use in downstream modules.

**Comment by sgratiy** [comment]
Chosen course of action:
If ontology file name is provided in the input to first module, will try to update ontology into this file if able to connect to LIMS in order to get updated list of stimuli. If cannot connect to LIMS then use file as is. 
If ontology file name is not provided will use the default ontology saved in the /defaults folder as a part of the package. 
The LIMS strategy provides the ontology file name, thus triggering the update of the ontology for each cell every time it is being reprocessed.
