### ISSUE TITLE
DAT converted nwb2 files have voltage and current flipped for CurrentClamp mode.

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#195]
In other words sweep.v holds current instead for voltage. 
To reproduce the issue:
convert the file
https://www.dropbox.com/s/3rk1lmupv9fhiq0/H19.28.004.12.06.dat?dl=0
and plot it with plot_ephys_nwb.py

**Comment by t-b** [comment]
Was that fixed already? Comparing 5003001 from
[H19.28.004.12.06.pdf](https://github.com/AllenInstitute/ipfx/files/3018207/H19.28.004.12.06.pdf)
with 
![Figure_1](https://user-images.githubusercontent.com/1185677/55162507-4bb34800-5168-11e9-947a-415e85014187.png)
looks correct.

Btw. the plot script did not work here. I've submitted PR #198 so that I could run the sript.

**Comment by sgratiy** [comment]
The issue is only with the CurrentClamp mode. Here you show the VoltageClamp. I mentioned that it the title, but should have been more explicit.

**Comment by t-b** [comment]
@sgratiy So I could now spot the error. I've updated the PR.

**Comment by t-b** [comment]
Fixed via #198.
