### ISSUE TITLE
test_x_nwb uses deprecated configuration option

### ISSUE THREAD

**Issue by gouwens** [AllenInstitute/ipfx#253]
I'm using pytest 5.0.0 with Python 3.7.3. When I try to run all the tests, I get the error:

```
____________________ ERROR collecting tests/test_x_nwb.py _____________________
test_x_nwb.py:26: in <module>
    if not pytest.config.getoption("--do-x-nwb-tests"):
/local1/anaconda3/envs/py3/lib/python3.7/site-packages/_pytest/main.py:187: in __getattr__
    warnings.warn(PYTEST_CONFIG_GLOBAL, stacklevel=2)
E   pytest.PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.

```

**Comment by sgratiy** [comment]
I am running pytest 4.6.3 with Python 3.6.8 and still get a deprecation warning. The original plan of switching all the way to 3.7 did not work because we did not have Docker set up for python 3.7 needed for running tests on Bamboo. Thus, I am using python 3.6. 
I will address the issue anyway, thanks for pointing out. If more problems will start creeping in related to python version though please consider creating a py3.6 environment.

**Comment by gouwens** [comment]
Sounds good. I guess it switched from a deprecation warning to an error from pytest 4.6 to 5. Like you said, probably good to address either way.

**Comment by gouwens** [comment]
I'm closing this since #257 was merged.
