### ISSUE TITLE
dealing with trailing zeros in sweeps

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/ipfx#274]
Wondering if we could have something built in here so that sweeps with long zero intervals at the end can be trimmed when they're loaded? I would think that would be preferred as the default behavior, or could be optional on load.

**Comment by gouwens** [comment]
I wonder what the best solution is. Some analyses may expect all the traces to be the same length. So in some analysis code I’ve written, I’ve NaN’d out the zeroes. But maybe returning only the actual data is preferable, and the code should be made aware of that.

**Comment by sgratiy** [comment]
If the issue is not the loading time, then you can get data without trailing zeros by choosing "recording" epoch. 
`sweep = Sweep(...)
`
`
sweep.select_epoch("recording")
`
I order to be able to choose data from various epochs, I needed to load all data into the sweep when it is being created. 
Other useful epoch are "stimulus" and "experiment", "test". The experiment is defined as stimulus epoch padded with 0.5 s before and after. You can find epoch definitions in epochs.py
We can define other epochs if you like
Does this address your needs? Sorry, for late response, I need to fix my github notifcation settings.

**Comment by tmchartrand** [comment]
The epochs does seem like a good solution to this problem, thanks! However, maybe the representation of the full sweep could use NaN rather than zero for missing data, as Nathan does. Then if user code tries to run an analysis without selecting the recording epoch they will be more likely to get an error rather than an incorrect result.

**Comment by sgratiy** [comment]
How about I set default epochs to "recording", and then turn all trailing zeros in the response to NaN?

**Comment by tmchartrand** [comment]
I could see either leaving the default as experiment or changing to recording, but either way think NaNs in the full sweep is the way to go.

**Comment by sgratiy** [comment]
Action plan:
- [x] Move get_data_set method into EphysDataSet
- [x] replace trailing zeros in sweeps responses with np.nan
- [x] select recording epochs to avoid processing Nan values
