### ISSUE TITLE
pip install no longer works

### ISSUE THREAD

**Issue by latimerb** [AllenInstitute/ipfx#279]
Hey all, I've been working on https://github.com/AllenInstitute/biophys_optimize which requires this package. I can no longer pip install it. Any idea why?

**Comment by gouwens** [comment]
The `biophys_optimize` package used to only use the `allensdk` package for feature extraction, but since feature extraction has moved into this package, I updated it to use `ipfx` instead. I changed the requirements of `biophys_optimize` mistakenly assuming that `ipfx` was available via pip install.

You do, though, need `ipfx` for the current version of `biophys_optimize` to work. Could you install it locally rather than by pypi - i.e., clone this repository and run `pip install -e .` in the top-level directory of `ipfx`? I can remove `ipfx` from the `requirements.txt` of `biophys_optimize` and add instructions for installing it to the readme.

**Comment by latimerb** [comment]
Yep, I can do that. Would be nice if everything was pip installable though, just to make it more adoptable for neuroscientists that may not have the tech background. For now this will work though. It's great work and I appreciate your help!

**Comment by bendichter** [comment]
I'd like to re-open this and request that ipfx be released on pypi. I would like my code to depend on this package and to be released on pypi. In order for that to work, this also needs to be released on pypi.

**Comment by wbwakeman** [comment]
I'll see if we can address this as part of the updates we are making in preparation for the June release
