### ISSUE TITLE
Document sweep qc tool options

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#295]
Research and document pros and cons of Sweep QC tool framework options.
Record on http://confluence.corp.alleninstitute.org/display/PP/Sweep+QC+Tool
Emphasis on simplicity and maintainability

**Comment by NileGraddis** [comment]
some notes

qt 5
--------
- all python (though calling to underlying C++). Supports real parellelization nonetheless.
- easy to build and deploy using [fbs](https://github.com/mherrmann/fbs-tutorial)
- errors in the C++ components are hard to debug
- styling not always straightforward
- GPL license (can use [pyside](https://doc.qt.io/qtforpython/) for lGPL, but then we lose fbs)
- probably the most built-in widgets of any python framework

electron
-----------
- javascript-based. This gives us access to libraries like react and d3 as well as styling through css. Also, performance ought to be better than pure python.
- needs to call python using e.g. [python-shell](https://www.npmjs.com/package/python-shell). This could get quite hairy since communication is across standard out
- MIT license

kivy
-----
- not sure how good deployment support is. Spot checking [an example application](https://github.com/snuq/Snu-Photo-Manager) makes it seem like install is pretty hairy on linux.
- good opengl integration

tkinter
--------
- part of the python stl

wx
---
- large widget collection

qt 4
-----
- we have a prior version of the app written up in python-qt4. 

qt 5 via c++
----------------
