### ISSUE TITLE
Add documentation for ipfx

### ISSUE THREAD

**Issue by dyf** [AllenInstitute/ipfx#36]
How to install and use ipfx
Links to examples
Link to ipfx.readthedocs.io

**Comment by NileGraddis** [comment]
I took a look through the docs.

landing:
- [ ] landing page says ipfx is python 2/3. We only support 3 now
- [ ] (nice to have) bolded class names in text should be links to apidocs
- [ ] the "analyze a data set" section should use the new dataset constructor
- [ ] the "analysis pipeline" section should be fleshed out and its value for external users described

installation:
- [ ] once ipfx is on pypi, update installation page to suggest pypi install
- [ ] mention that `git-lfs` is needed to get our test data

credits:
- [ ] add contributors

data sets and stimuli:
- [ ] fix weird bolding and broken links
- [ ] intro can be tightened up a bit
- [ ] use new dataset constructor
- [ ] when mentioning NWB in text, should expand the initialism and link to https://www.nwb.org/ (at least the first time on a page). People might not know what an NWB file is.

gallery of examples: 
Some of these could use:
- [ ] more textual description
- [ ] more explicit variable names
- [ ] a more detailed introduction when using allensdk to access data - otherwise it is sprung on people out of nowhere

qc and analysis pipeline:
- [ ] this whole page is missing. I think it is supposed to be the "how do I replicate the AIBS pipeline" guide. We could also use it to give examples of how to setup inputs for and run the argschema modules.

api documentation:
- [x] Our docstrings seem to be rendering. :fire:

history:
- [ ] Another stub. We decided to use the Github releases, right? Let's just replace this page with a link

--------------------------------

README.md:
- [ ] we can remove the deprecation warning
- [ ] add a link to the docs and examples
- [ ] add links to new contrib guidelines
