### ISSUE TITLE
Use load_namespaces=True when writing MIESNWBData

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#408]
MIES now has a nds-mies extension.  In order to use this and not get a namespace key error, need to use:

```
load_namespaces=True
```

when writing this data.
Reference: See https://pynwb.readthedocs.io/en/stable/tutorials/general/extensions.html

MIES namespace yaml file is in this MIES PR:
https://github.com/t-b/ndx-MIES/pull/1/files

**Comment by wbwakeman** [comment]
@njmei  implemented this for the new extension for extracellular electrophysiology here:
https://github.com/AllenInstitute/AllenSDK/blob/2bebc646bb12d22da7da5a4b07ddd4985039df66/allensdk/brain_observatory/ecephys/nwb/__init__.py#L8

**Comment by NileGraddis** [comment]
taking a look at this as I have some time.

**Comment by NileGraddis** [comment]
@wbwakeman has made test data at: /allen/aibs/technology/waynew/ephys/output1/Z/ephys/set1/

**Comment by NileGraddis** [comment]
In order to set load_namespaces to True, I've had to make modifications to hdmf and pynwb. Those live here:
https://github.com/NileGraddis/hdmf/tree/ipfx-408-namespaces
https://github.com/NileGraddis/pynwb/tree/ipfx-408-namespaces

While getting these merged in is right long-term, we can also subclass in ipfx as a temporary workaround.

**Comment by NileGraddis** [comment]
currently blocked by https://github.com/hdmf-dev/hdmf/issues/354
