### ISSUE TITLE
Membrane time constant fit does not meet tolerance

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#50]
Commonly the RMSE for the fit is much greater than the RMSE preventing calculation of the membrane time constant.

**Comment by gouwens** [comment]
Could you clarify this a bit more? The check is there so that bad fits won't be included in the average time constant for the cell. Is the issue (1) that all the subthreshold sweeps are failing the RSME check, or (2) that it seems like a lot of individual sweeps fail this check?

Option (1) could be a problem if we are too strict for too many cells, but (2) is only a problem (I think) if there are good fits that are still getting rejected.
