### ISSUE TITLE
Feature extraction code for analysis in Gouwens, Sorensen, et al. - Cell, 2020

### ISSUE THREAD

**Issue by gonzalobenegas** [AllenInstitute/ipfx#536]
It would be helpful to have access to the code used to extract electrophysiological features for the analysis in the Gouwens, Sorensen, et al. - Cell, 2020 paper. The code availability statement points to the ipfx library but it would be great to have more information about specific scripts, parameters and QC steps.

Additionally, it would be helpful to have direct access to the extracted features besides from the nwb files, similarly to how [this portal](https://portal.brain-map.org/explore/classes/multimodal-characterization/multimodal-characterization-mouse-visual-cortex) contains links to both fastqs, bams and gene count matrices.

**Comment by xanderladd** [comment]
I believe you can find them here: https://github.com/AllenInstitute/biophys_optimize

**Comment by tmchartrand** [comment]
@gouwens can you help?

**Comment by gouwens** [comment]
The specific script used is this one:
https://github.com/AllenInstitute/ipfx/blob/master/ipfx/bin/run_feature_vector_extraction.py

We run it with basically default parameters - we do use the "LIMS" option because it finds the files and sweep QC information stored in our internal database. We used the `lims-passed-except-delta-vm` sweep QC option, as well, because some of our earlier Patch-seq experiments used intentionally shortened protocols that did not necessarily have the membrane potential return to zero. But otherwise the sweep QC are as defined in our white paper:
http://help.brain-map.org/download/attachments/8323525/CellTypes_Ephys_Overview.pdf?version=2&modificationDate=1508180425883&api=v2

Some extracted electrophysiology features are viewable in the Patch-seq web application:
https://knowledge.brain-map.org/data/1HEYEW7GMUKWIQW37BO/specimens/list
It is not possible to download the features from the web application yet, but that is something that is planned for a future update.

**Comment by gonzalobenegas** [comment]
Thanks, this answers my questions!
